apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # echo -n 'my-user' | base64 (see mysql-chart-values-minikube.yaml)
  db_user: bXktdXNlcg== 
  # echo -n 'my-pass' | base64 (see mysql-chart-values-minikube.yaml)
  db_pwd: bXktcGFzcw==
  # echo -n 'my-app-db' | base64 (see mysql-chart-values-minikube.yaml)
  db_name: bXktYXBwLWRi
  # echo -n 'secret-root-pass' | base64 (see mysql-chart-values-minikube.yaml)
  db_root_pwd: c2VjcmV0LXJvb3QtcGFzcw==
